# Generated by Django 6.1.1 on 2026-09-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='board',
            new_name='column',
        ),
        migrations.AlterField(
            model_name='kbboard',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
