# Generated by Django 6.1.1 on 2026-09-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='start',
            new_name='start_date',
        ),
    ]
