# Generated by Django 6.1.1 on 2026-09-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_task_completed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardinvitation',
            old_name='receiver',
            new_name='invitee',
        ),
        migrations.RenameField(
            model_name='boardinvitation',
            old_name='sender',
            new_name='inviter',
        ),
        migrations.AlterField(
            model_name='boardinvitation',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor')], max_length=20),
        ),
    ]
